# Generated by Django 5.1.7 on 2026-02-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("degree", models.CharField(max_length=100)),
                ("field", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("year", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("role", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=120)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HighlightStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=180)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="IdeaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("stage", models.CharField(blank=True, max_length=80)),
                ("summary", models.TextField(blank=True)),
                ("impact", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="ideas/documents/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="ideas/images/"),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("caption", models.TextField(blank=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document")],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("home", "Home"),
                            ("story", "Story"),
                            ("work", "Work"),
                            ("research", "Research"),
                            ("library", "Library"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="assets/")),
            ],
            options={
                "ordering": ["section", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProgramItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("period", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PublicationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, max_length=32)),
                ("item_type", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(blank=True, max_length=80)),
                ("summary", models.TextField(blank=True)),
                ("external_url", models.URLField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="publications/documents/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="publications/images/"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("title", models.CharField(max_length=180)),
                ("location", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("nationality", models.CharField(blank=True, max_length=80)),
                ("current_focus", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "collaboration_blurb",
                    models.TextField(
                        blank=True, help_text="Displayed on the contact page."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile/images/"
                    ),
                ),
                (
                    "cv_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload CV or profile document.",
                        null=True,
                        upload_to="profile/documents/",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core Competency"),
                            ("technical", "Technical Skill"),
                            ("language", "Language"),
                            ("interest", "Professional Interest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ["category", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("year", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField()),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="portal.experienceitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
