# Generated by Django 5.1.7 on 2026-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_educationitem_experienceitem_highlightstat_ideaitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
