# Generated by Django 5.2 on 2026-02-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alter_contactmessage_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExperienceHighlight",
        ),
    ]
