# Generated by Django 5.2 on 2026-02-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_delete_experiencehighlight"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteprofile",
            name="passion_text",
            field=models.TextField(
                blank=True,
                default="I am deeply passionate about startup and innovation-driven enterprise development as a transformative force for economic growth and societal progress. My professional journey has strengthened my commitment to building ecosystems where ideas evolve into sustainable ventures and entrepreneurs are empowered to create meaningful impact.\n\nI am particularly driven by the process of creating, designing, and innovating new solutions - not only within existing systems but by reimagining how businesses can operate, scale, and contribute to national development. I believe startups are not merely small businesses; they are engines of structural transformation.\n\nMy focus extends beyond institutional support - I am committed to mentoring emerging entrepreneurs, guiding business owners in strategic thinking, helping them refine business models, and enabling them to transition from survival-driven enterprises to innovation-driven organizations.\n\nI aspire to contribute to the development of inclusive and sustainable innovation ecosystems where creativity, technology, and policy intersect to generate long-term value.",
                help_text="Editable passion content shown on the Passion page.",
            ),
        ),
        migrations.AddField(
            model_name="siteprofile",
            name="resume_text",
            field=models.TextField(
                blank=True,
                default="TILAHUN ALENE TERFIE\n\nAddis Ababa, Ethiopia\nEmail: tilahunalenee@gmail.com | Phone: +251 941 883 746\n\nPROFESSIONAL PROFILE\nStrategic Innovation and Public Policy Expert with over 15 years of progressive leadership experience in education reform, national innovation systems development, startup ecosystem support, and digital government transformation. Currently serving as Senior Expert in Startup and Innovative Enterprise Development at the Ministry of Innovation and Technology, Ethiopia.\n\nDemonstrated expertise in designing and implementing national innovation frameworks, leading multi-sector coordination initiatives, managing large-scale ICT and e-government projects, and mentoring technology-based startups. Strong academic foundation with multiple degrees in History, Economics, Management, and Public Policy Studies.\n\nRecognized for strategic leadership, institutional capacity building, and driving systemic transformation across public institutions.\n\nCORE COMPETENCIES\nStartup Ecosystem Development\nInnovation Policy and System Design\nE-Government and Digital Transformation\nStrategic Leadership and Team Management\nPublic Sector Reform\nProject and Program Management\nCurriculum Development and Education Reform\nStakeholder Engagement and Intergovernmental Coordination\nMentorship and Capacity Building\nProblem-Solving and Analytical Thinking\n\nPROFESSIONAL EXPERIENCE\nSenior Expert - Startup and Innovative Enterprise Development\nMinistry of Innovation and Technology (May 2022 - Present)\nProvide structured training, mentorship, and acceleration support to technology-based startups.\nDesign and implement national startup support mechanisms.\nFacilitate networking opportunities between startups, investors, and ecosystem actors.\nSupport innovation-driven enterprises in scaling sustainable business models.\nContribute to strengthening Ethiopia's national innovation ecosystem.\n\nProject Manager - ICT and E-Government Initiatives\nMinistry of Innovation and Technology (Oct 2021 - May 2022)\nLed national-level ICT projects with a multidisciplinary technical team.\nManaged implementation of e-government (e-service) systems.\nEnabled more than 300 government institutions to provide online services.\nStrengthened institutional digital service delivery frameworks.\nCoordinated cross-sector stakeholders to ensure project success.\n\nTeam Leader - Councils and Regions Coordination Directorate\nMinistry of Innovation and Technology (2016 - 2021)\nLed a five-member core team coordinating establishment of national innovation systems across regional states.\nSuccessfully facilitated the establishment of Science, Technology, and Innovation institutions in all regions of Ethiopia.\nDelivered training, workshops, and policy advisory services to regional governments.\nEngaged high-level regional leaders to institutionalize innovation governance frameworks.\n\nEducation Curriculum Coordinator\nAddis Ababa Education Office (2014 - 2016)\nLed coordination of local curriculum implementation across schools.\nSupervised 150+ education experts, teachers, and administrators.\nCollaborated with international development partners.\nLaunched community libraries to enhance student learning access.\nReceived certificates of recognition for contributions.\n\nTeacher - History and Social Sciences\nAmhara Education Bureau (2013 - 2014)\nTaught primary and secondary school students.\nDeveloped engaging instructional methods.\nContributed to curriculum enhancement initiatives.\n\nEDUCATION\nMA in Public Policy Studies - Ethiopian Civil Service University (2021)\nBA in Management - Bahir Dar University (2022)\nBA in Economics - Arsi University (2021)\nBA in History and Heritage Management - Debre Markos University (2013)\n\nLANGUAGES\nAmharic - Fluent\nEnglish - Advanced\n\nTECHNICAL AND ADDITIONAL SKILLS\nStrategic Planning and Policy Analysis\nICT Project Oversight\nStartup Mentorship and Acceleration\nPublic Sector Innovation Design\nBasic Full-Stack Development Skills\nLeadership and Institutional Capacity Building\n\nPROFESSIONAL REFERENCES\nAvailable upon request.",
                help_text="Editable resume content shown on the Resume page.",
            ),
        ),
    ]
