# Generated by Django 5.2 on 2026-02-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_blogitem_passioncontent_resumecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleItem",
            fields=[],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portal.blogitem",),
        ),
        migrations.CreateModel(
            name="InsightItem",
            fields=[],
            options={
                "verbose_name": "Insight",
                "verbose_name_plural": "Insights",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portal.blogitem",),
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("portal.blogitem",),
        ),
        migrations.AlterModelOptions(
            name="publicationitem",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Research and Publication",
                "verbose_name_plural": "Research and Publications",
            },
        ),
    ]
