# Generated by Django 5.1.7 on 2026-07-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_articleitem_insightitem_newsitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('issued_on', models.CharField(blank=True, max_length=120)),
                ('expires_on', models.CharField(blank=True, max_length=120)),
                ('section', models.CharField(choices=[('short_term', 'Short-term'), ('long_term', 'Long-term'), ('professional', 'Professional'), ('academic', 'Academic'), ('other', 'Other')], default='other', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/documents/')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/images/')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
    ]
